### ISSUE TITLE
Reuse make targets of skycoin/skycoin repository when appropriate

### ISSUE THREAD

**Issue by olemis** [simelo/pyskycoin#10]
Current `Makefile` includes a `build-libc` target to build `libskycoin` C library . It is wrong because :

- build steps may change and maintenance of the most up-to-date procedure would have to be duplicated in `pyskycoin` .
- even if source files are located under `skycoin/` folder , its dependencies are looked up in global `GOPATH`

Make targets in `skycoin/skycoin` should be reused and used consistently without an extra dependency upon system `GOPATH`.

**Comment by stdevStark** [comment]
@olemis this one should be closed , fixed in dfd0696

**Comment by olemis** [comment]
ok thanks
