### ISSUE TITLE
[ci] Definitive Travis matrix build

### ISSUE THREAD

**Issue by olemis** [simelo/pyskycoin#18]
- Builds for Python `3.4` , `3.5` , `3.6`
- Code style checks 
  * Exclude `skycoin.py` and generated files
- Do not include `libskycoin.a` in sdist
  * in other words , include Skycoin (go) source code and integrate precondition make targets into `setup.py` code

**Comment by stdevEclipse** [comment]
All go code in sdist? OK.
And go as a requirement I think.

**Comment by olemis** [comment]
@stdevEclipse macos builds failing for Python 3 e.g. https://travis-ci.org/simelo/pyskycoin/jobs/401499702
