### ISSUE TITLE
Does not contain make install

### ISSUE THREAD

**Issue by stdevHan** [simelo/pyskycoin#26]
In the `https://github.com/simelo/pyskycoin#installation`, it says that just to install you must run `make install` and already, but this gives error, saying that install does not exist

**Comment by stdevEclipse** [comment]
Sorry about that.
Already created pull request for that.
To install:
python setup.py install
To install and keep making changes to the library:
python setup.py develop
However, using tox takes care of everythin. Just call:
tox
This will execute the tests with latest changes made to the library.
